//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class livre
    {
        public int Id { get; set; }
        public string titre { get; set; }
        public byte[] image { get; set; }
        public string auteur { get; set; }
        public string desc { get; set; }
        public Nullable<double> prix { get; set; }
        public Nullable<int> stock { get; set; }
    }
}
